environment/scripts/composer.sh
Handy when using Laravel and creating Laravel projects.
=> Adding composer's vendor directory to system PATH

Vagrantfile, scripts/always.sh, scripts/mailcatcher.sh
Closes #41 
Added mailcatcher - pretty sweet
=> Adding mailcatcher as default SMTP server for PHP

scripts/mailcatcher.sh, scripts/sass.sh
Remove documentation generation
fixes #68
=> Speed up mailcatcher install

Vagrantfile, scripts/php-xhprof.sh
=> NEW php-xhprof support

scripts/apache.sh
=> Use --prefer-dist to prevent hitting GitHub API

scripts/apache.sh
See https://github.com/silverstripe/silverstripe-installer/pull/82
=> Removing index.php rename (not needed anyomore)

Vagrantfile, scripts/apache.sh, scripts/install-silverstripe.sh
Added a nicer SS installer.
Usage:
`./silverstripe-installer.ss [-v 3.x-dev] [-d /vagrant/public_html] [-i mycustom/installer]`
=> Creating a nicer SS installer

scripts/always.sh
=> Clearing SS cache on provision

scripts/composer.sh
Hopefully this will stop false reports to packagist for installs on provisions of dev machines
=> Tweak composer provisioner to set up some global config options

Vagrantfile
=> Moving to centos-7.1 box

Vagrantfile, scripts/mysql-57.sh
Added an installer for mysql 5.7 for debugging purposes.
=> NEW mysql-57 installer

scripts/mysql-57.sh
Fixing bugs in mysql 5.7 installer
=> FIX MySQL 5.7 installer now works

scripts/xdebug.sh
Supersedes #84; closes #84; closes #77
=> Improvements to xdebug (continued)

scripts/php.sh
Fixes #77 
Add an argument for PHP provisioner to increase max exec time
=> Adding max execution time to PHP provisioner

Vagrantfile, scripts/gulp.sh
=> NEW Gulp installer

Vagrantfile
whoop! Puppetlabs at last with a box we can use
=> Upgrade base box to centos 7.2

scripts/composer.sh
An updated installer for composer following their installer method detailed here: https://getcomposer.org/download/
=> Use new composer installer method

Vagrantfile
Pretty simple, really.
If you've got cachier installed, use it.
=> NEW Add cachier support

Vagrantfile
See https://www.vagrantup.com/docs/virtualbox/configuration.html for info
=> Add support for linked clones out of the box

scripts/node.sh
=> Move to install node 6 by default

scripts/composer.sh, scripts/install-silverstripe.sh
(my) vagrant provision can't handle backspaces ie: clearing the line and echoing progress nicely.
This makes the output a bit clearer during provision.
=> Turn off composer progress during provision

scripts/php.sh
=> Adding support for PHP7
