BetterBrief/vagrant-skeleton

README.md
Vagrantfile
environment/scripts/php-53.sh
environment/scripts/php-55.sh
environment/scripts/php-56.sh
environment/scripts/php-mcrypt.sh

* Markdown has been changed slightly so there's no horizontal scrollbar in the README viewer.
* The "Purpose" column on the README was a bit much and didn't have much use, so it's been removed
* The default version of PHP has been shifted to PHP 5.6, with 5.5 and 5.3 scripts provided. All `php-x.sh` scripts have been suffixed with their versions.
* Mcrypt is now installed by default for 5.5 >=

PHP versioning, little cleanup

---

scripts/php-54.sh
scripts/php-55.sh
scripts/php-56.sh

Unit tests need php-tidy - this installs it as required
php-tidy doesn't appear to be in the CentOS repos so we have to install through EPEL

FIX Add php-tidy for unit tests

---

README.md
Vagrantfile
scripts/php-54.sh
scripts/php-55.sh
scripts/php-56.sh
scripts/xdebug.sh

Before going completely crazy. Here's the final version with only one commit.

Enable xdebug for local debugging.

---

scripts/bower.sh

Most of our usage on the box is as root user.
This explicitly allows the root user to use bower without repeatedly using the `--allow-root` flag

Allow root bower use out of the box

---

scripts/bootstrap.sh

When running `yum update` the mounting of shared folders breaks.
This fixes the problem. fixes #81

Adding fix to allow `yum update` to work

---

Vagrantfile
scripts/apache.sh
scripts/grunt.sh
scripts/install-silverstripe.sh
scripts/mount-webroot.sh

With the introduction of the new SilverStripe installer script, a problem has occurred where the webroot wasn't always mounted into `/var/www/html` as the apache installer also takes responsibility for this, but was running before the SS installer had (due to PHP / composer deps for SS install)
This change pulls the webroot mounting into it's own script.
The first thing the provisioner will do is mount the webroot if it exists, php and apache can then install, then bring in composer.
After that the SS installer can run and it calls the `mount-webroot` script, thus resolving this problem.

Separating webroot mounting logic from apache installer

---

scripts/mount-webroot.sh

When the `/vagrant/www` folder already exists on provision, the folder mounting script attempts to symlink it to `/var/www/html` but apache isn't installed yet and so `/var/www` doesn't exist.
Therefore we need to create it and then symlink it.

Fixing issue with webroot mounter running before apache is installed

---

scripts/node.sh

Using instructions from https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora
The epel repo only seems to install ^0.10
This also turns off bin-links too (which is useful for windows hosts with shared file systems), though has some side-effects for global installs that now need to use `--bin-links` to get the CLI tools working "properly"

Updating node installer

---

scripts/php-mcrypt.sh

Previously the mcrypt installer would only work if php 5.4 was installed.
Now it works with our supported versions (5.4, 5.5, 5.6)

FIX PHP-mcrypt installer works with various version of PHP

---

scripts/bower.sh
scripts/grunt.sh
scripts/gulp.sh
scripts/less.sh

Turning off `bin-links` globally means global installs don't get symlinked to the users path.
All global installs need symlinks, this PR makes sure that happens

FIX Make sure npm global installs use bin-links

---

scripts/composer.sh

More often than not composer is run in root context on the vagrant machine. this is safe enough to do as it's sandboxed.

Stop Composer super user warnings

---

scripts/php-mcrypt.sh

Mcrypt is deprecated in php-7 so this stops the script trying to install it on PHP 7 based systems.

Skip php-mcrypt install on php7

---

Vagrantfile

Vagrant have updated their docs at some point and have a new recommended syntax for version comparison: https://www.vagrantup.com/docs/virtualbox/configuration.html#linked-clones

Use back version compare syntax as per docs

---

.env

you can put the `.env` a dir above the webroot if you want, so we might as well support this out of the box like we do for SS 3

Add root .env for better SS 4 support

---

Vagrantfile

Instead of always incrementing the minor version of centos when there's a release, this will allow us to just hook onto the latest 7 release.

Use bento/centos-7 box

---

Vagrantfile
scripts/install-silverstripe.sh

- Install PHP 7 by default
- Install SS 4.x-dev by default (when using install-silverstripe script)
- Install into `./project` dir so that `mount-webroot.sh` will mount the `public/` dir correctly

Be more friendly to SS4 (and 4.1, which has a `public` web dir

---

scripts/php.sh

- Allow php 7.2 installs (now that it's supported in webtatic)
- Allow installing with a generic "7" argument to get latest PHP 7 install (eg: `./scripts/php -v 7`)

Allow php7.2 installs

---

scripts/mount-webroot.sh

Default installs now go into `/vagrant/project` (even for SS3) so we need to make sure that's a valid webroot option when mounting

Add /vagrant/project as a valid webroot option

---

_ss_environment.php

At the moment we manage both a `_ss_environment.php` and `.env` file to support running SS 3 and SS4 in the vagrant machine.
However, quite often this means users edit the wrong file and think they've made a change when they haven't - confusing.
This attempts to make the `.env` the "source of truth" by making the `_ss_environment.php` file parse the `.env` file.
I've gone for rudimentary `.env` parsing rather than trying to pull in a composer package or what not.
Also, I've realised the default file_to_url_mapping is now wrong as `project/public` is the default project dir now; so I've updated this to search for a set of candidates as well.

Better cross version environment management

---

README.md
Vagrantfile

~~The 7 box is now discontinued.~~
https://app.vagrantup.com/chef/boxes/centos-7.0
https://app.vagrantup.com/bento/boxes/centos-7.0
Vagrant 1.9 doesn't play nice with the new Bento boxes

Define missing Vagrant min version

---

Vagrantfile

I'm running vagrant 2.0 on one of my machines and it works fine, so we should loosen this constraint

FIX Min vagrant version of 2.0

---

scripts/composer.sh

Set the composer bin dir from config settings, which is a better way of doing this and means we don't have to hard code bin dirs into our config :)
composer sometimes stores these in `~/.composer` or `~/.config/composer/` so it's best not to hard code :)

Define composer bin dir from config
